# Generated by Django 2.1.7 on 2019-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='value',
            field=models.FloatField(),
        ),
    ]
